name: Manually triggered end-to-end test
on:
  workflow_dispatch:
    inputs:
      instance_identifiers:
        description: 'Comma separated list of instance identifiers'
        required: true
        type: string
        default: 'sunnydale'
      image_tag:
        description: 'UI container image tag to test'
        required: true
        type: string
        default: 'latest'
      backend_base_url:
        description: 'Base url for backend API'
        required: true
        type: string
        default: 'https://api.paths.kausal.dev/v1'
      nr_workers:
        description: 'How many test workers to use'
        required: false
        type: number
        default: 2

jobs:
  e2e_test:
    name: Run tests
    uses: ./.github/workflows/e2e-image.yaml
    with:
      image: $${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE_REPO }}:${{ inputs.image_tag }}
      backend_base_url: ${{ inputs.backend_base_url }}
      build_id: manual
      s3_endpoint: ${{ vars.BUILD_S3_ENDPOINT }}
      s3_bucket: ${{ vars.BUILD_S3_BUCKET }}
    secrets: inherit
